ionos-cloud/cluster-api-provider-proxmox

- CONTRIBUTING.md
- README.md
- docs/Development.md
- docs/Usage.md
#20 (actually a PR)
The Proxmox brand guidelines https://www.proxmox.com/images/proxmox/Proxmox-Corporate-Brandguideline-2018.pdf request that products are referred to by their full or abbreviated names.
Honour this request by updating our usage of the word Proxmox to refer to Proxmox VE.
none needed
> docs: Refer to Proxmox VE correctly

- docs/Usage.md
fixes #22 
Updated ink to IPAMProivder to a pre-release version.
> use pre-release for IPAMProvider

- internal/service/vmservice/ip.go
- pkg/kubernetes/ipam/ipam.go
- pkg/kubernetes/ipam/ipam_test.go
IPAddressClaim is not paused due to the pausing implementation was not correct:
The correct check is the clusterName label:
https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/blob/b8ccdf8c362cd51ee120e50f8ec2b637f02e3755/internal/controllers/ipaddressclaim.go#L180
> Fixes pause of IPAddressClaim

- .github/workflows/code-qa-sonarcloud.yaml
- .github/workflows/test.yml
`on.pull_request` executes the workflow out of a forked repository. This means the `SONAR_TOKEN` secret will not be available and therefore the workflow will fail. By changing it to `on.pull_request_target`, the workflow definition (and code) from the trusted original repository is run and the secret will be available.
See https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
This should fix issues with failed SonarCloud runs on external PRs like in https://github.com/ionos-cloud/cluster-api-provider-proxmox/actions/runs/7240484604/job/19723537444
> ci: run sonarcloud via pull_request_target

- pkg/cloudinit/network.go
- pkg/cloudinit/network_test.go
- pkg/cloudinit/types.go
Towards #29 
I decided to create multiple PRs, for better and faster reviews.
This PR:
- Adds dhcp options in the network-config for cloud-init
> Adjust cloudinit to support dhcp

- cmd/main.go
In This PR https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/42, the machine webhook is introduced/
but the binding was not implemented.
> Bind Proxmoxmachine Webhook

- internal/service/vmservice/find.go
- internal/service/vmservice/find_test.go
- internal/service/vmservice/helpers_test.go
- internal/service/vmservice/vm.go
> Fix the VM name lazy intialize

- config/manager/manager.yaml
These TODOs are unnecessary.
Sonarcloud is unhappy about long-term TODOs. Since we're not actually ever intending on doing these, delete them so that Sonarcloud doesn't get confused.
> config: remove useless TODOs

- .github/workflows/test.yml
`verify` running in `pull_request_target` context verifies the upstream rather than the PR.
https://github.com/ionos-cloud/cluster-api-provider-proxmox/actions/runs/7627247798/job/20775470951
Moved `verify` to `go_test`, as `verify` also needs to checkout the PR. Whilst it's possible for those two to run in parallel, in practice `verify` is very fast anyway and we're avoiding copying the checkout dance which wouldn't be good for maintainability.
> fix(ci): fold verify under go_test

- pkg/cloudinit/network.go
- pkg/cloudinit/network_test.go
The ipv6 gateway needs to be wrapped in quotation marks, otherwise it can produce invalid yaml.
Example (invalid, caused by ::, ::1 is fine, can be checked by a yaml linter like https://www.yamllint.com):
```yaml
network:
version: 2
renderer: networkd
ethernets:
eth0:
match:
macaddress: BC:24:11:75:4E:D2
dhcp4: false
dhcp6: false
addresses:
- 2a01:7e01:e003:3b04:ffff::/64
routes:
- to: '::/0'
via: 2a01:7e01:e003:3b04::
nameservers:
addresses:
- 2a01:7e01:e003:3b00::6464
```
Results into:
> fix(cloudinit): wrap ipv6 addresses in quotation marks

- Makefile
I wanted to test the webhook package, but found there was no easy way of running the tests because it needs envtest binaries.
Add Makefile variable `WHAT` that controls what tests should be run. Defaults to `./...`.
`WHAT` must be a valid go package specification.
Also updated the envtest k8s version to 1.28.0, because the go.mod uses 1.28.X.
I ran `make test` with different values of `WHAT` locally.
> fly-by: Allow specifying packages to test

- .github/workflows/test.yml
Sonarcloud thinks that every branch is "main" (see https://sonarcloud.io/project/branches_list?id=ionos-cloud_cluster-api-provider-proxmox)
This is an attempt to fix that
Warning: the check run here uses the workflow from main, so I cant be sure if this works. I'd be happy to receive other suggestions
> ci: fix sonarcloud scan pr source

- docs/Usage.md
used fresh clusterctl config. 
Got:
```
> clusterctl init --infrastructure proxmox --ipam in-cluster
Fetching providers
Error: failed to get provider components for the "in-cluster" provider: failed to read "ipam-components.yaml" from provider's repository "ipam-in-cluster": release not found for version download, please retry later or set "GOPROXY=off" to get the current stable release: 404 Not Found
```
> Fixing Usage docs

- .github/workflows/e2e.yml
fixes #120
Converts the `pull_request` trigger into a `pull_request_target` trigger.
This works the same way the `test` workflow works.
The version in `main` is triggered on `pull_request`, so the e2e tests in *this PR* will not get triggered.
Unfortunately, we will only be able to fully verify it once it's in `main`.
> github/e2e: run e2e tests on pull_request_target

- docs/Troubleshooting.md
If you have multiple interfaces in your cluster, with some interfaces only available to some nodes, calico can fail to guess the right ip range/interface to use for IPVS. I've added some troubleshooting documentation for this case.
No tests required from our side.
> docs/Troubleshooting: add calico ipvs interface detection issue

- pkg/cloudinit/network.go
- pkg/cloudinit/network_test.go
This very little templating error made it into production. It creates the same yaml key multiple times, which makes the last VRF device win in cloudinit.
I've added testcases for multiple vrfs, so we don't get any repeats.
> cloudinit: fix multiple vrf device templating

- Dockerfile
- Makefile
- docs/Development.md
The test harness started failing on my end. This is because setup-envtest now depends on golang 1.22. At the moment I get segfaults when testing with golang 1.22.
While at it, I've also fixed documentation and docker build.
Docker image built.
Test harness now runs again with golang 1.21
> Go 1.21 touchups

- docs/Troubleshooting.md
- docs/Usage.md
ref: #52
Documentation on environment variable differences in CAPMOX and Proxmox Image Builder VE.
None at all.
> docs: add image builder envrionment variable warning

- docs/Troubleshooting.md
- docs/advanced-setups.md
https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/144
Documentation for IPv6 and kube-vip (and cilium).
We rolled out IPv6 only clusters. We should update our kube-vip manifest versions, but I had no time to test that.
> docs: document ipv6 only cluster kube-vip version

- .github/workflows/e2e.yml
fixes #199
1. `labeled` and `unlabeled` added to trigger types so that the label can be modified after the PR is submitted
2. e2e job runs if the PR does not have the `skip e2e` label.
As this modifies a `pull_request_target` workflow it will only take effect once merged to main.
> e2e: skip workflow on 'skip e2e' label

- templates/cluster-class.yaml
Was getting
**.spec.ipv4Config: expected map, got &{[10.10.10.10-10.10.10.20]}**
Assuming it is because of this recent [commit](https://github.com/ionos-cloud/cluster-api-provider-proxmox/commit/032869f1590c5623ede6aecce6cfb444cbe9f855) which did some changes to the cluster-class example.
Removes the **.addresses** from the patching configuration. With these changes the validation error no longer occurs on my setup.
> Fix ipv4config error in example cluster-class

- templates/cluster-template-external-creds.yaml
When using the `cluster-template-external-creds` template with `clusterctl`, the following error is obtained:
```
Error: failed to parse yaml: failed to unmarshal the 3rd yaml document: "apiVersion: v1\nstringData:\n  secret: REDACTED\n  token: REDACTED\n  url: https://REDACTED:8006\nkind: Secret\nmetadata:\n  name: \"kind-monk2\"-proxmox-credentials\n  labels:\n    platform.ionos.com/secret-type: \"proxmox-credentials\"\n": error converting YAML to JSON: yaml: line 7: did not find expected key
```
Fixing the `name` key as outlined by this commit resolves the issue.
> cluster-template-external-creds: Fix name of the Secret

- .mockery.yaml
#234
We decided against forcing one boilerplate to keep the copyright lines correct and because it's questionable whether generated files are subject to copyright.
However, we forgot to actually remove the boilerplate file from mockery config.
`make mockgen` no longer fails.
> mockery: don't use boilerplate

- api/v1alpha1/proxmoxcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclustertemplates.yaml
- pkg/scope/cluster.go
This PR:
Fixes an issue, if a user provided a ProxmoxCluster manifest with external creds with only the name of secret
> USe cluster namespace if no namespace provided in credentials Ref

- docs/Development.md
Addresses https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/253
*Issue #, if available:* https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/253
*Description of changes:* Adding paragraph to documentation regarding how to debug using `delve`
*Testing performed:* N/A
> Updating Development.md to include remote debugging

- internal/webhook/proxmoxmachine_webhook.go
- templates/cluster-class-calico.yaml
- templates/cluster-class-cilium.yaml
- templates/cluster-template-cilium.yaml
The webhook fails cause the `spec.network` is nil
Fixes #255
> Fix CNI cluster templates

- docs/Usage.md
- docs/advanced-setups.md
Now that https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/278 has been merged, we are able to restrict the rights of the CAPMOX API user much more. 
We have tested this permission set extensively on our internal test cluster.
Unfortunately, it is not possible for me to create an end-to-end test as I do not have access to the end-to-end test infrastructure.
> Add documentation for Proxmox RBAC with least privileges

- .github/workflows/container-image.yaml
When forking the repository for development purposes, the github action workflow inside the fork will try upload the built image to ghcr.io/**ionos-cloud**/cluster-api-provider-proxmox, which results in a permission error: `ERROR: denied: permission_denied: The requested installation does not exist.`
This can be avoided by instead of having a hardcoded image name in the workflow, one dynamically takes the GITHUB_REPOSITORY variable and converts it into lowercase (for those who have Github usernames with one or more capital letters). Consequentially, every fork will push to its own registry without permission issues, while the main repository keeps working just like before.
Verified workflow in my fork. It manages to publish ghcr images to my …
> Improve docker build workflow in forks

- README.md
- api/v1alpha1/conditions_consts.go
- clusterctl-settings.json
- internal/controller/proxmoxcluster_controller.go
- internal/controller/suite_test.go
- internal/inject/inject.go
- internal/service/vmservice/delete.go
- internal/service/vmservice/delete_test.go
- internal/service/vmservice/power_test.go
- metadata.yaml
- pkg/cloudinit/metadata.go
- pkg/cloudinit/metadata_test.go
- pkg/scope/machine.go
- test/e2e/config/proxmox-ci.yaml
- test/e2e/config/proxmox-dev.yaml
> Release 0.6.0

- cmd/main.go
- internal/tlshelper/roots.go
- internal/tlshelper/roots_test.go
- pkg/scope/cluster.go
*Issue #, if available:* #192
- Add environment variables / flags to main process to enable certificate checking / providing root-ca when talking to Proxmox
- Add secret keys for the Proxmox credential secret to enable certificate checking / providing root-ca when talking to Proxmox
- Retain default (TLS-Insecure) in order not to introduce a breaking change (RFC)
> Add optional TLS certificate checking when talking to Proxmox

- config/manager/manager.yaml
The current `securityContext` of the `manager` deployment doesn't meet the Pod Security Profile "restricted", which makes it impossible to run in "restricted" namespaces.
The `cluster-api` deployments also set this value, for example [here](https://github.com/kubernetes-sigs/cluster-api/blob/2a7d61df5924f714f4271caa677e4a0a9f529da6/config/manager/manager.yaml#L76) 
With this change implemented, a deployment to a 'restricted' namespace will be successful. It shouldn't change the current behaviour for non-restricted namespaces.
> Add securityContext.seccompProfile.type: RuntimeDefault to manager deployment to meet restricted Pod security profile

- Makefile
in regards to the follwing issue:
[https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/194](url)
What was changed: Describe the specific change:
Added --fail-fast to the Ginkgo command in the test-e2e target of the Makefile.
Ensures the e2e test suite halts immediately upon encountering a failure.
Why the change was made:
Saves compute resources and time by stopping further tests when a failure is detected.
Further information about the --fail-fast flag can be found here: [https://onsi.github.io/ginkgo/](url)
> feat: Add fail-fast behavior to Ginkgo in test-e2e

- internal/inject/inject_test.go
- internal/service/vmservice/bootstrap.go
- internal/service/vmservice/bootstrap_test.go
- internal/service/vmservice/helpers_test.go
- pkg/cloudinit/metadata.go
- pkg/cloudinit/metadata_test.go
- pkg/cloudinit/types.go
- pkg/ignition/enrich.go
It would be very helpful to have access to the Kubernetes version specified in a machine's `spec.version` in the cloud-init/ignition metadata. With this information, it is possible to install Kubernetes version specific resources in cloud-init/ignition.
I used [this PR](https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/347) as a template, but I'm not sure if the way to control the injection is particularly elegant.
I would suggest injecting the field without a flag in the default or always passing the value of `MetadataSettings` completely to `cloudinit.NewMetadata` so that you don't have to add another argument for each flag.
I would be very happy to receive feedback from the maintainers on this suggestion and would then also carry out the desired …
> Add kubernetes-version/injectKubernetesVersion to Metadata

- internal/inject/inject_test.go
- internal/service/vmservice/bootstrap.go
- internal/service/vmservice/bootstrap_test.go
- pkg/cloudinit/network.go
- pkg/cloudinit/network_test.go
- pkg/cloudinit/types.go
- pkg/ignition/enrich.go
- pkg/ignition/enrich_test.go
- pkg/ignition/network.go
- pkg/ignition/network_test.go
- pkg/types/network.go
This PR moves the struct `NetworkConfigData` out of the cloudinit pkg,
Since ignition also uses the struct to generate network configuration, `NetworkConfigData` becomes a common type and can be moved to a standard package.
Closes #341
> 🌱  Refactoring: move NetworkConfigData out of cloudinit pkg

- .github/workflows/test-external.yml
- .github/workflows/test.yml
This adds a workflow that runs tests on PRs from forks. The Test workflow instead writes a comment that reminds o/ approval and highlights potentially suspicious files.
Ref https://github.com/ionos-cloud/cluster-api-provider-proxmox/security/advisories/GHSA-qhwh-qr65-jwm3
> workflows: move testing external PRs to own workflow

- .github/dependabot.yml
- .github/workflows/test-external.yml
- .github/workflows/test.yml
- Dependabot: scan hack/tools
- Test: switch to sonarqube-scan-action as sonarcloud-github-action is deprecated
> Misc fixes

- .github/ISSUE_TEMPLATE/bug_report.md
> Include Proxmox version in the bug report

- api/v1alpha1/proxmoxmachine_types.go
- api/v1alpha1/proxmoxmachine_types_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachinetemplates.yaml
this fixes a small oversight in #343 and actually validates the individual tags against what is accepted by the API
https://github.com/proxmox/pve-common/blob/master/src/PVE/JSONSchema.pm#L706
```
our $PVE_TAG_RE = qr/[a-z0-9_][a-z0-9_\-\+\.]*/i;
```
> fix: add tag validation to MatchTags

- .github/workflows/e2e.yml
- test/e2e/capmox_test.go
- test/e2e/data/infrastructure-proxmox/cluster-template-ci.yaml
- test/e2e/suite_test.go
This PR enable logging for the e2e tests so we can check what's happening.
> Enable logging for e2e tests

- .github/workflows/e2e.yml
- .github/workflows/test.yml
`ref` can be raced between approval and checkout by pushing a commit between approval and checkout. `sha` always refers to the triggering commit, which is safe.
https://github.com/ionos-cloud/cluster-api-provider-proxmox/security/advisories/GHSA-qhwh-qr65-jwm3
> .github/workflows/{e2e,test}: check out sha instead of ref

- api/v1alpha1/proxmoxmachine_types.go
- api/v1alpha1/proxmoxmachine_types_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachinetemplates.yaml
#174
* Fix `ProxmoxMachineSpec` validation rules
* Previous rule required `full` to be always set to `true` and did not validate for `storage` being set
* Move validation rules from `ProxmoxMachine` to `VirtualMachineCloneSpec`
* Moving validation rules to `VirtualMachineCloneSpec` also adds them to other resources where it is embedded that users interact with directly
* Remove default value from `VirtualMachineCloneSpec.Format`
* Having `format` default to `raw` prevents making linked clones on storages that support it
* `make test`
* Manually deploying multiple clusters with and without linked clones enabled
> Add support for linked clones
