.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/report_vulnerability.md

Change issue template

---

internal/service/vmservice/find.go
internal/service/vmservice/find_test.go
internal/service/vmservice/helpers_test.go
internal/service/vmservice/vm.go

Fix the wrong name

---

.github/ISSUE_TEMPLATE/release.md

Release Template

---

CODEOWNERS

Add Philipp  as Maintainer

---

README.md
docs/Development.md
docs/Troubleshooting.md
docs/Usage.md

~This line will also need to be updated:
https://github.com/ionos-cloud/cluster-api-provider-proxmox/blob/main/docs/Development.md?plain=1#L78~

docs: update for cluster-api v1.6.1

---

api/v1alpha1/proxmoxmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachinetemplates.yaml
internal/controller/proxmoxmachine_controller.go
internal/controller/proxmoxmachine_controller_test.go
internal/webhook/proxmoxmachine_webhook.go
internal/webhook/proxmoxmachine_webhook_test.go
pkg/scope/machine_test.go
sonar-project.properties

Increase code coverage by adding tests in Uncovered lines.

Add unit tests

---

README.md

Add slack Channel

---

.github/ISSUE_TEMPLATE/release.md

We do not have the resources to maintain release branches.

github: update release template

---

README.md

#48
Now that we have e2e tests, @mcbenjemaa suggested we should have a badge. This adds the requested badge.
Viewing in browser.

readme: add e2e badge

---

.github/workflows/lint.yml

The lint action is broken, due to the update

Fix Lint action

---

docs/Usage.md

Following: https://github.com/kubernetes-sigs/cluster-api/issues/10107#issuecomment-1932170020

Document IPAM

---

hack/tools/go.mod
hack/tools/go.sum
hack/tools/tools.go

While developing a bigger PR, I found that yamlfmt grew some new dependencies.
Ran `make yamlfmt` succesfully.

yamlfmt: add missing dependencies

---

.github/workflows/e2e.yml

Cleanup of kind clusters after e2e runs

Add post run to cleanup kind clusters from e2e runner

---

.github/workflows/e2e.yml

Fix cleanup 

---

api/v1alpha1/proxmoxcluster_types.go
api/v1alpha1/proxmoxmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_proxmoxmachinetemplates.yaml

The CRD comments had some inconsistencies in capitalization, punctuation and grammar.
I'm not 100% on the `'s` grammar rules so please correct me if I'm wrong.

docs: Adjust CRD field comments

---

docs/Troubleshooting.md

Just a bit of advice on how to delete a machine that is stuck deleting.
Stuck machine deleted.

docs/Troubleshooting: document machine deletion deadlocks

---

internal/service/vmservice/vm.go
internal/service/vmservice/vm_test.go
pkg/proxmox/client.go
pkg/proxmox/goproxmox/api_client.go
pkg/proxmox/goproxmox/api_client_test.go
pkg/proxmox/goproxmox/errors.go
pkg/proxmox/proxmoxtest/mock_client.go

- Check cloud-init status
- Through error state if cloud-init fails

Check cloud-init status as part of machine provisioning 

---

.yamllint

Removed a duplicate line in .yamllint config file.

refactor: remove duplicate line in yamllint config file

---

docs/Usage.md

IPAM provider is now part of clusterctl, there's no need to add it to clusterctl config

Remove unnecessary config

---

clusterctl-settings.json

fix  #249
This is the only required change since this is a patch release.

release v0.5.1

---

docs/Development.md

Remove unnecessary task from  Development.md

---

.github/workflows/e2e-comment.yml
.github/workflows/e2e.yml

The idea is to read a label  with prefix `skipe-e2e/*`what comes after the prefix will be skipped. 
There are 3 Labels for now: 
- `skip-e2e/Flatcar` will skip tests labeled with 'Flatcar'
- `skip-e2e/Generic` will skip tests labeled with 'Generic'
- `skip-e2e/none` will not skip any tests

Skip e2e based on label

---

go.mod
go.sum

bump cluster-api to 1.8.5

---

.github/workflows/lint.yml
.golangci.yml
hack/tools/go.mod
hack/tools/tools.go
internal/controller/proxmoxmachine_controller.go
internal/service/scheduler/vmscheduler.go
internal/service/scheduler/vmscheduler_test.go
internal/service/taskservice/error_test.go
internal/service/vmservice/bootstrap_test.go
internal/service/vmservice/delete.go
internal/service/vmservice/delete_test.go
internal/service/vmservice/helpers_test.go
internal/service/vmservice/power_test.go
internal/service/vmservice/utils_test.go
internal/webhook/proxmoxcluster_webhook.go
internal/webhook/proxmoxcluster_webhook_test.go
internal/webhook/webhook_suite_test.go
pkg/proxmox/goproxmox/api_client_test.go

1. Ported the api_client tests that didn't get merged into the public release (from @65278)
2. More taskservice tests
3. More vmservice tests
4. Configured goimports + a reformatting of offending files

Misc improvements

---

cmd/main.go

Resolves: #420 
Add flags to the manager to be able to set various leader election configurations. These leader-election flags are supported by the [manager](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options). Moreover most projects in the cluster-api umbrella already support them.

Add leader election lease related flags

---

docs/advanced-setups.md

This PR adds documentation on the v0.7 features:
* Custom Allowed Nodes
* Custom IP Pool Config
Closes https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/426

Write docs for the new v0.7 features

---

internal/controller/proxmoxcluster_controller.go

Check on the Cluster instead and patch the cluster status.
Tested in infra-mvp ✅ 
Closes #484

Fix the cluster failed state bug, by checking over the root cluster and patch it

---

clusterctl-settings.json
go.mod
hack/tools/go.mod
internal/controller/proxmoxcluster_controller.go

https://pkg.go.dev/vuln/GO-2025-3563
https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/484
Cherry-picks the bugfix.
Bumps go to 1.23.8 to fix the CVE.

Release v0.7.1

---

clusterctl-settings.json

#509 
Just an interim maintenance release to update some dependencies including two minor security issues.
https://github.com/ionos-cloud/cluster-api-provider-proxmox/security/dependabot/10
https://github.com/ionos-cloud/cluster-api-provider-proxmox/security/dependabot/11

release v0.7.2
